### PR TITLE
Remove second instance of onyphe ranges

### PR DESCRIPTION
**Pull request by szepeviktor**
Spotted with `grep '^#'` that there are two copies.

### CODE REVIEW

**Comment by szepeviktor** [comment]
There is a little difference between the top and the bottom lists.
```diff
--- /onyphe/top  2023-08-03 12:16:04.456441439 +0000
+++ /onyphe/bottom  2023-08-03 12:16:04.456441439 +0000
@@ -1,12 +1,10 @@
 5.135.173.112/28
 5.196.102.64/28
-15.204.52.61/32
 37.59.54.188/32
 37.59.55.63/32
 37.187.153.85/32
 37.187.153.218/32
 37.187.215.240/28
-45.43.33.218/32
 51.79.20.65/32
 51.79.21.18/32
 51.79.21.113/32
@@ -24,9 +22,8 @@
 94.23.1.70/32
 94.23.61.227/32
 94.23.208.106/32
-139.99.9.160/32
-142.4.218.114/32
 144.217.24.0/28
+144.217.24.16/28
 144.217.201.192/28
 146.59.184.0/28
 147.135.236.160/28
```

**Comment by wravoc** [comment]
Thanks for bringing this to my attention. The Onyphe IP list has been collapsed and updated.

**Comment by szepeviktor** [comment]
Glad to contribute.

**Comment by szepeviktor** [comment]
A second thought: it would be nice to have those IP ranges in separate files - e.g. in `sources/` directory - and a GitHub action that sorts and concatenates them into `scanners`.

**Pull request closed without merging**
